name: docker-build
description: Build docker image
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo_name }}
inputs:
  repo_name:
    description: Name of Docker repository
    required: false
    default: Dockerhub